name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        ENGINE_VERSION: [5.3.0, 5.4.0, 5.5.0, 5.6.1, latest]

    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
    - name: test
      run: docker-compose up --exit-code-from sut
